version: '3.8'

services:

  mongodb:
    image: controlemix/api-rest:latest
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile.image 
    ports:
      - '27017:27017'
      - '3000:3000'
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_DATABASE=apidb  
    volumes:
      - mongodataapirest:/data/db
    networks:
      - api-rest-network

networks:
  api-rest-network:
    driver: bridge

volumes:
  mongodataapirest: