version: '3.8'

services:

  mongodb:
    image: controlemix:api-rest-mongodb
    build:
      context: .
      dockerfile: Dockerfile.jammy  
    ports:
      - '27017:27017'
      - '3000:3000'
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_DATABASE=apidb  
    volumes:
      - mongodataapirest:/data/db
    networks:
      - api-rest-network

networks:
  api-rest-network:
    driver: bridge

volumes:
  mongodataapirest:
  # appapirest:


      # - appapirest:/usr/app
      # - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:rw
      # - ./pm2.json:/usr/app/pm2.json:rw
      # - ./dist:/usr/app/dist:rw