version: '3.8'

networks: 

  mynetwork:
    driver: bridge

services:

  mymongodb:
    image: mongo:latest
    restart: always
    container_name: MY_MONGODB    
    build:
      context: .    
    restart: always
    environment:
      - MONGODB_DATABASE="desafio"
    ports:
      - 27017:27017
    networks: 
      - mynetwork      

  mynodejs:
    container_name: MY_NODEJS
    build:
      context: .
    environment:
      - DATABASE_HOST="mongodb://mymongodb:27017/desafio"
    ports:
      - 3000:3000
    ports:
      - 3000:3000
    depends_on:
      - mymongodb
    links:
      - mymongodb
    networks: 
      - mynetwork
