version: '3.8'

networks: 

  mynetwork:
    driver: bridge

services:

  mymongodb:
    image: mongo:latest
    restart: always
    container_name: MY_MONGODB    
    environment:
      - MONGODB_DATABASE="desafio"
    ports:
      - 27017:27017
    networks: 
      - mynetwork

  # mymongoexpress:
  #   image: mongo-express
  #   restart: always
  #   container_name: MY_MONGO_EXPRESS
  #   ports:
  #     - 5081:8081
  #   env_file:
  #     - ./mongo-express.env
  #   depends_on:
  #     - mymongodb
  #   links:
  #     - mymongodb
  #   networks: 
  #     - mynetwork

  mynodejs:
    container_name: MY_NODEJS
    build:
      context: .
    environment:
      - DATABASE_HOST="mongodb://mymongodb:27017/desafio"
    ports:
      - 3000:3000
    depends_on:
      - mymongodb
    links:
      - mymongodb
    networks: 
      - mynetwork


    # volumes:
      # - .:/usr/app
      # - /usr/app/node_modules